# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'maya-client.ios' do
pod 'CocoaAsyncSocket'  
pod 'M13ProgressSuite'
end

